# Generated by Django 3.1.13 on 2021-08-31 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblUser',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('check_password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tbl_user',
                'managed': False,
            },
        ),
    ]
